CREATE TABLE IF NOT EXISTS films (
    id numeric   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY   NOT NULL,
    name varchar(500)   NOT NULL,
    description varchar(200)   NOT NULL,
    releaseDate TIMESTAMP WITH TIME ZONE   NOT NULL,
    duration numeric   NOT NULL,
    rating_id numeric,
    CONSTRAINT pk_films PRIMARY KEY (
        id
     )
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id numeric  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY   NOT NULL,
     name  varchar(100)   NOT NULL,
    CONSTRAINT  pk_genre  PRIMARY KEY (
         genre_id 
     )
);

CREATE TABLE IF NOT EXISTS  film_genre  (
     id  numeric  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY   NOT NULL,
     film_id  numeric   NOT NULL,
     genre_id  numeric   NOT NULL,
    CONSTRAINT  pk_film_genre  PRIMARY KEY (
         id 
     )
);

CREATE TABLE IF NOT EXISTS  ratings  (
     id  numeric  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY   NOT NULL,
     name  varchar(100)   NOT NULL,
     description  varchar(200)   NOT NULL,
    CONSTRAINT  pk_ratings  PRIMARY KEY (
         id 
     )
);

CREATE TABLE IF NOT EXISTS  users  (
     id  numeric  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  NOT NULL,
     login  varchar(100)   NOT NULL,
     email  varchar(100)   NOT NULL,
     name  varchar(100)   NOT NULL,
     birthday  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT  pk_users  PRIMARY KEY (
         id 
     )
);

CREATE TABLE IF NOT EXISTS  likes  (
     id  numeric GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY    NOT NULL,
     film_id  numeric   NOT NULL,
     user_id  numeric   NOT NULL,
    CONSTRAINT  pk_likes  PRIMARY KEY (
         id 
     )
);

CREATE TABLE IF NOT EXISTS  friends  (
     id  numeric GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY    NOT NULL,
     user_id_1  numeric   NOT NULL,
     user_id_2  numeric   NOT NULL,
     is_confirmed  bool,
    CONSTRAINT  pk_friends  PRIMARY KEY (
         id 
     )
);

alter table  films 
drop constraint if exists  fk_films_rating_id ;

ALTER TABLE  films  ADD CONSTRAINT  fk_films_rating_id  FOREIGN KEY( rating_id )
REFERENCES  ratings  ( id );

alter table  film_genre 
drop constraint if exists  fk_film_genre_film_id ;

ALTER TABLE  film_genre  ADD CONSTRAINT  fk_film_genre_film_id  FOREIGN KEY( film_id )
REFERENCES  films  ( id );

alter table  film_genre 
drop constraint if exists  fk_film_genre_genre_id ;

ALTER TABLE  film_genre  ADD CONSTRAINT  fk_film_genre_genre_id  FOREIGN KEY( genre_id )
REFERENCES  genre  ( genre_id );

alter table  likes 
drop constraint if exists  fk_likes_film_id ;


ALTER TABLE  likes  ADD CONSTRAINT  fk_likes_film_id  FOREIGN KEY( film_id )
REFERENCES  films  ( id );

alter table  likes 
drop constraint if exists  fk_likes_user_id ;

ALTER TABLE  likes  ADD CONSTRAINT  fk_likes_user_id  FOREIGN KEY( user_id )
REFERENCES  users  ( id );

alter table  friends 
drop constraint if exists  fk_friends_user_id_1 ;

ALTER TABLE  friends  ADD CONSTRAINT  fk_friends_user_id_1  FOREIGN KEY( user_id_1 )
REFERENCES  users  ( id );

alter table  friends 
drop constraint if exists  fk_friends_user_id_2 ;

ALTER TABLE  friends  ADD CONSTRAINT  fk_friends_user_id_2  FOREIGN KEY( user_id_2 )
REFERENCES  users  ( id );


INSERT INTO PUBLIC.GENRE
(NAME)
SELECT 'Комедия'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.GENRE
    WHERE NAME = 'Комедия'
);
INSERT INTO PUBLIC.GENRE
(NAME)
SELECT 'Драма'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.GENRE
    WHERE NAME = 'Драма'
);
INSERT INTO PUBLIC.GENRE
(NAME)
SELECT 'Мультфильм'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.GENRE
    WHERE NAME = 'Мультфильм'
);
INSERT INTO PUBLIC.GENRE
(NAME)
SELECT 'Триллер'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.GENRE
    WHERE NAME = 'Триллер'
);
INSERT INTO PUBLIC.GENRE
(NAME)
SELECT 'Документальный'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.GENRE
    WHERE NAME = 'Документальный'
);
INSERT INTO PUBLIC.GENRE
(NAME)
SELECT 'Боевик'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.GENRE
    WHERE NAME = 'Боевик'
);


INSERT INTO PUBLIC.RATINGS
(NAME, DESCRIPTION)
SELECT 'G', 'G'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.RATINGS
    WHERE NAME = 'G'
);
INSERT INTO PUBLIC.RATINGS
(NAME, DESCRIPTION)
SELECT 'PG', 'PG'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.RATINGS
    WHERE NAME = 'PG'
);
INSERT INTO PUBLIC.RATINGS
(NAME, DESCRIPTION)
SELECT 'PG-13', 'PG-13'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.RATINGS
    WHERE NAME = 'PG-13'
);
INSERT INTO PUBLIC.RATINGS
(NAME, DESCRIPTION)
SELECT 'R', 'R'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.RATINGS
    WHERE NAME = 'R'
);
INSERT INTO PUBLIC.RATINGS
(NAME, DESCRIPTION)
SELECT 'NC-17', 'NC-17'
FROM (SELECT 1) AS dummy_table
WHERE NOT EXISTS (
    SELECT 1
    FROM PUBLIC.RATINGS
    WHERE NAME = 'NC-17'
);

